import React from 'react';


const Lists = {
  instrumentOptions: [
    'Guitar(6)',
    'Guitar(7)',
    'Guiter(8)',
    'Acoustic-Guitar',
    'Bass(4)',
    'Bass(5)',
    'Acoustic-Bass',
    'Double-Bass',
    'Drums',
    'Vocals',
    'Piano',
    'Keyboard',
    'Violin',
    'Saxophone',
    'Cello',
    'Flute'
  ],
  locationOptions: [
    'Montgomery (AL)',
    'Juneau (AK)',
    'Phoenix (AZ)',
    'Little Rock (AR)',
    'Sacramento (CA)',
    'Denver (CO)',
    'Hartford (CT)',
    'Dover (DE)',
    'Tallahassee (FL)',
    'Atlanta (GA)',
    'Honolulu (HI)',
    'Boise (ID)',
    'Springfield (IL)',
    'Indianapolis (IN)',
    'Des Moines (IA)',
    'Topeka (KS)',
    'Frankfort (KY)',
    'Baton Rouge (LA)',
    'Augusta (ME)',
    'Annapolis (MD)',
    'Boston (MA)',
    'Lansing (MI)',
    'Saint Paul (MN)',
    'Jackson (MS)',
    'Jefferson City (MO)',
    'Helena (MT)',
    'Lincoln (NE)',
    'Carson City (NV)',
    'Concord (NH)',
    'Trenton (NJ)',
    'Santa Fe (NM)',
    'Albany (NY)',
    'Raleigh (NC)',
    'Bismarck (ND)',
    'Columbus (OH)',
    'Oklahoma City (OK)',
    'Salem (OR)',
    'Harrisburg (PA)',
    'Providence (RI)',
    'Columbia (SC)',
    'Pierre (SD)',
    'Nashville (TN)',
    'Austin (TX)',
    'Salt Lake City (UT)',
    'Montpelier (VT)',
    'Richmond (VA)',
    'Olympia (WA)',
    'Charleston (WV)',
    'Madison (WI)',
    'Cheyenne (WY)'
  ],
  skillLvls: [
    'Beginner',
    'Hobbyist',
    'Intermediate',
    'Advanced',
    'Professional'
  ],
  styles: [
    'Blues','Classic-Rock','Country','Dance','Disco','Funk','Grunge',
 'Hip-Hop','Jazz','Metal','New-Age','Oldies','Other','Pop','R&B',
 'Rap','Reggae','Rock','Techno','Industrial','Alternative','Ska',
 'Death-Metal','Soundtrack','Euro-Techno','Ambient',
 'Trip-Hop','Vocal','Fusion','Trance','Classical',
 'Instrumental','Acid','House','Gospel',
 'Noise','Alt-Rock','Bass','Soul','Punk','Space','Meditative',
 'Instrumental-Pop','Instrumental Rock','Gothic',
 'Darkwave','Techno-Industrial','Electronic','Pop-Folk',
 'Eurodance','Dream','Southern-Rock','Comedy','Cult','Pop/Funk','Jungle',
 'Cabaret','New-Wave','Psychadelic','Rave','Showtunes',
 'Lo-Fi','Tribal','Acid-Punk','Acid Jazz','Polka','Retro',
 'Musical','Rock','Hard-Rock','Folk','Folk-Rock',
 'National Folk','Swing','Fast-Fusion','Bebob','Latin','Revival',
 'Celtic','Bluegrass','Avantgarde','Gothic-Rock','Progressive-Rock',
 'Psychedelic Rock','Symphonic Rock','Slow-Rock','Big-Band',
 'Chorus','Easy-Listening','Acoustic','Chanson',
 'Opera','Chamber-Music','Sonata','Symphony','Satire','Slow-Jam','Club','Tango','Samba',
 'Folklore','Ballad','Power Ballad','Rhythmic Soul','Freestyle',
 'Duet','Punk-Rock','Acapella','Euro-House','Dance-Hall', 'Pop-Punk',
  'Alt-Metal', 'Post-Hardcore', 'Hardcore', 'Math-Rock'
  ],
  commitment: [
    'Low(1-3)',
    'Mid-low(3-6)',
    'Mid(6-10)',
    'Mid-High(10-14)',
    'High(14+)'
  ],
  post_type: [
    'Band',
    'Side-Project',
    'Recording',
    'One-off (gig)',
    'Shed'
  ],
  makeOptions(arr){
    return arr.map((item, key) => <option key={key} value={item}>{item}</option>)
  },

}

export default Lists;